BAG of WORDS

In [ ]:
# Bag of Words Stop words (a,the,is,and,I,me,etc,He ,She )
#articles---a,an,the

#prepositions---in,on,at,by,near,under,over,above,below etc
 # conjunctions-----although, because, before, if, since, though, unless, until, when, while, whereas, wherever, whether, after, as, as if, as long as, as much as, as soon as, as though, by the time, even if, even though, in order that, in case, lest, once, provided that, rather than, since, so that, than, that, till, whenever, where, wherever, without
# stop word is excluded
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# 1. Define your text data (Corpus)
corpus = [
    "I love cats",
    "I love dogs",
    "Cats and dogs are great"
]

# 2. Initialize the CountVectorizer
vectorizer = CountVectorizer()

# 3. Fit and transform the corpus into a BoW matrix
bow_matrix = vectorizer.fit_transform(corpus)

# 4. Extract the vocabulary (unique words)
words = vectorizer.get_feature_names_out()

# 5. Display the result as a readable table (DataFrame)
df_bow = pd.DataFrame(bow_matrix.toarray(), columns=words)

print("Vocabulary:", words) 
print("\nBag of Words Matrix:")
print(df_bow)


Vocabulary: ['and' 'are' 'cats' 'dogs' 'great' 'love']

Bag of Words Matrix:
   and  are  cats  dogs  great  love
0    0    0     1     0      0     1
1    0    0     0     1      0     1
2    1    1     1     1      1     0


In [2]:
# Stop word is included
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
    "I love cats",
    "I love dogs",
    "I love both cats and dogs"
]


tokenizer = Tokenizer()

tokenizer.fit_on_texts(sentences)

bow_matrix = tokenizer.texts_to_matrix(sentences, mode='count')


print("Unique Words Index:", tokenizer.word_index)
print("\nBag of Words Matrix:")
print(bow_matrix)


Unique Words Index: {'i': 1, 'love': 2, 'cats': 3, 'dogs': 4, 'both': 5, 'and': 6}

Bag of Words Matrix:
[[0. 1. 1. 1. 0. 0. 0.]
 [0. 1. 1. 0. 1. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1.]]
